.PHONY: clean All

All:
	@echo "----------Building project:[ ProtectedMembersClass - Debug ]----------"
	@cd "/Users/Bryan/Documents/OnLineClasses/CPP/inheritance/ProtectedMembersClass/ProtectedMembersClass" && "$(MAKE)" -f  "ProtectedMembersClass.mk"
clean:
	@echo "----------Cleaning project:[ ProtectedMembersClass - Debug ]----------"
	@cd "/Users/Bryan/Documents/OnLineClasses/CPP/inheritance/ProtectedMembersClass/ProtectedMembersClass" && "$(MAKE)" -f  "ProtectedMembersClass.mk" clean
