.PHONY: clean All

All:
	@echo "----------Building project:[ Template - Debug ]----------"
	@cd "Template" && "$(MAKE)" -f  "Template.mk"
clean:
	@echo "----------Cleaning project:[ Template - Debug ]----------"
	@cd "Template" && "$(MAKE)" -f  "Template.mk" clean
