.PHONY: clean All

All:
	@echo "----------Building project:[ ChallengeOpt2 - Debug ]----------"
	@cd "/Users/Bryan/Documents/OnLineClasses/CPP/Section8/ChallengeOpt2/ChallengeOpt2" && "$(MAKE)" -f  "ChallengeOpt2.mk"
clean:
	@echo "----------Cleaning project:[ ChallengeOpt2 - Debug ]----------"
	@cd "/Users/Bryan/Documents/OnLineClasses/CPP/Section8/ChallengeOpt2/ChallengeOpt2" && "$(MAKE)" -f  "ChallengeOpt2.mk" clean
