.PHONY: clean All

All:
	@echo "----------Building project:[ Factorial - Debug ]----------"
	@cd "/Users/Bryan/Documents/OnLineClasses/CPP/Functions/Factorial/Factorial" && "$(MAKE)" -f  "Factorial.mk"
clean:
	@echo "----------Cleaning project:[ Factorial - Debug ]----------"
	@cd "/Users/Bryan/Documents/OnLineClasses/CPP/Functions/Factorial/Factorial" && "$(MAKE)" -f  "Factorial.mk" clean
