.PHONY: clean All

All:
	@echo "----------Building project:[ Mystring-insertion-extraction - Debug ]----------"
	@cd "/Users/Bryan/Documents/OnLineClasses/CPP/OperatorOverloading/Mystring-insertion-extraction/Mystring-insertion-extraction" && "$(MAKE)" -f  "Mystring-insertion-extraction.mk"
clean:
	@echo "----------Cleaning project:[ Mystring-insertion-extraction - Debug ]----------"
	@cd "/Users/Bryan/Documents/OnLineClasses/CPP/OperatorOverloading/Mystring-insertion-extraction/Mystring-insertion-extraction" && "$(MAKE)" -f  "Mystring-insertion-extraction.mk" clean
